import keras
from path import paths
from utils import generate_noisy_image, display_img
import numpy as np
import argparse
import random

def generate_img(selected_numbers,mean,std,img_number,show_img):
    
    noisy_img = generate_noisy_image(mean,std)
    noisy_img = np.reshape(noisy_img,(1,794))
    
    for index in range(img_number):
        random_number_index = random.randint(0,len(selected_numbers)-1)
        noisy_img[0][784+selected_numbers[random_number_index]] = 1
        generated_img = np.reshape(model(noisy_img)[0][0:784],(28,28))
        display_img(generated_img,show_img=show_img,path = paths['generated_imgs'],save_fig=True,title="generated_"+str(index)+"_img.png")
        print(f"image {index+1} generated")
        print(f"Number to be generated {selected_numbers[random_number_index]}")
        noisy_img[0][784+selected_numbers[random_number_index]] = 0
         
def parse_opt():
    
    parser = argparse.ArgumentParser()
    parser.add_argument('--mean',type=float,default=0.5,help="The noisy img will be generated following a normal distribution with the set mean.")
    parser.add_argument('--std',type=float,default=0.3,help="The noisy img will be generated following a normal distribution with the set standard deviation.")
    parser.add_argument('--img_number',type=int,default=20,help="The number of images to be generated by the algorithm.")
    parser.add_argument('--show_img',action='store_true')
    
    opt = parser.parse_args()
    print(vars(opt))
    
    return opt

if __name__ == "__main__":

    model = keras.models.load_model(paths['model']+'/'+'generator.keras')
    opt = parse_opt()
    selected_numbers = [0,5]
    print('Starting to generate images...')
    generate_img(selected_numbers, **vars(opt))
        